### PR TITLE
Allocate and copy null terminator when copying fingerprint string

### LINKED ISSUE #540: Certificate fingerprint length is not null terminated
When copying a user provided certificate fingerprint, the string is not copied with a null terminator which results in the error similar to

`[0708/100210.214:WARNING:web_transport_fingerprint_proof_verifier.cc(89)] Invalid fingerprint length
[0708/100210.214:WARNING:quic_transport_client.cc(55)] Failed to add a certificate fingerprint: B5:1B:D3:56:4A:D7:37:47:9C:0F:63:7F:E8:D5:28:75:54:8C:F3:17:B4:D7:8E:BB:AE:DB:C7:9B:69:E4:E1:01ýýýýÝ`

https://github.com/open-webrtc-toolkit/owt-client-native/blob/7a812df8a6567efa096f2deb09a6edfb307a11ba/talk/owt/sdk/conference/conferencewebtransportchannel.cc#L102

### PR DESCRIPTION
**Pull request by brgavino**
Fix for null terminator when copying the certificate fingerprint string, when setting the fingerprint manually.

fixes #540

### CODE REVIEW

File: talk/owt/sdk/conference/conferencewebtransportchannel.cc [hunk 1]
```diff
@@ -100,9 +100,9 @@ void ConferenceWebTransportChannel::Connect() {
   int fingerprint_idx = 0;
   for (auto fingerprint : trusted_fingerprints) {
     quic_params.server_certificate_fingerprints[fingerprint_idx]->fingerprint =
-        new char[fingerprint.length()];
+        new char[fingerprint.length()+1];
     memcpy((void*)(quic_params.server_certificate_fingerprints[fingerprint_idx]->fingerprint),
```
Comment (taste1981) [inline talk/owt/sdk/conference/conferencewebtransportchannel.cc:104]: memset after allocation.

Comment (brgavino) [reply talk/owt/sdk/conference/conferencewebtransportchannel.cc:104]: I believe in modern C++ this will be zero-initialized by default, as a value-type array: https://en.cppreference.com/w/cpp/language/zero_initialization

**Review by taste1981 — APPROVED** [review]
