### PR TITLE
Fix issue #201: windows client cannot create share window stream

### LINKED ISSUE #201: windows client cannot create share window stream

### PR DESCRIPTION
**Pull request by taste1981**
Fix #201

### CODE REVIEW

File: talk/owt/sdk/base/windowcapturer.cc [hunk 1]
```diff
@@ -63,30 +63,31 @@ void BasicWindowCapturer::WindowCaptureThreadFunc(void* pThis) {
 }
 
 bool BasicWindowCapturer::CaptureThreadProcess() {
-  if (!capture_started_) {
+  while (!capture_started_) {
```
Comment (jianjunz) [inline talk/owt/sdk/base/windowcapturer.cc]: Retry limitation for the loop?

Comment (jianjunz) [reply talk/owt/sdk/base/windowcapturer.cc]: Will you add a limitation here or it's ready to merge?

Comment (taste1981) [reply talk/owt/sdk/base/windowcapturer.cc]: adding a limit will cause issue as we don't know when user will finally confirm the window to be shared. the thread will be destroyed.
